In [4]:
#factorial
n=int(input("enter number"))
i=1
f=1
while i<=n:
    f=f*i
    i=i+1
    
print(f)


enter number12
479001600


In [3]:
#factorial of 6
n=int(input("enter the number"))
i=1
while i<=10:
    print(n,"*",i,"-",n*i)
    i=i+1

enter the number6
6 * 1 - 6
6 * 2 - 12
6 * 3 - 18
6 * 4 - 24
6 * 5 - 30
6 * 6 - 36
6 * 7 - 42
6 * 8 - 48
6 * 9 - 54
6 * 10 - 60


In [2]:
#series of square
n=int(input("enetr the number"))
i=1
while i<=n:
    print(i*i,end=" ")
    i=i+1

enetr the number25
1 4 9 16 25 36 49 64 81 100 121 144 169 196 225 256 289 324 361 400 441 484 529 576 625 

In [9]:
#reverse series
n=int(input("enter the number"))
r=0
while n>0:
    r=n%10
    print(r,end="")
    n=n//10
    
    

enter the number10
01

In [11]:
n=int(input("enter no of terms u want in fibonacci series"))
f1=0
f2=1
print(f1)
print(f2)
term=3
while term<=n:
    f3=f1+f2
    print(f3)
    f1=f2
    f2=f3
    term=term+1


enter no of terms u want in fibonacci series15
0
1
1
2
3
5
8
13
21
34
55
89
144
233
377


In [4]:
#palindrome Number 
print("Enter the Number: ")
num=int(input())
rev=0
temp=num
while temp>0:
    rem=temp%10
    rev=rem+(rev*10)
    temp=int(temp/10)
if rev==num:
    print("\nIt is a P Number")
else:
    print("\nIt is not a P Number")

Enter the Number: 
121

It is a P Number


In [6]:
n=121
num=n
rv=0

while n>0:
    r=n%10
    rv=rv*10+r
    n=n//10


if rv==num:
    print("palindrome")
else:
    print("not palindrome")



palindrome


In [7]:
#armstrong
n=int(input("enter number"))
num=n
sum=0

while n>0:
    r=n%10
    sum=sum+r**3
    n=n//10


if sum==num:
    print("Armstrong")
else:
    print("not armstrong")


enter number125
not armstrong


In [8]:
#only even number (armstrong)
n=125
while n>0:
    r=n%10
    if r%2==0:
        print(r,end=" ")
    n=n//10


2 

In [11]:
#sum (Armstrong)
n=125
sum=0
while n>0:
    r=n%10
    sum=sum+r
    n=n//10
    
print(sum)


8


# STRING
#anything written in '',"",''' ''',"""""" is string
#used to manage text, character data etc


In [12]:
name = 'amruta'
name2 = "amruta"
name
name == name2

True

In [13]:
n="123456789"
type(n)
roll_no = "IT1002"
type(roll_no)


str

In [15]:
#in string index starts with 0 to n-1
#0-n-1 indexing called as forward indexing
#when you want to access last element you can perform backward indexing (negative indexing)
#negative indexing starts with -1



In [18]:
name ="amruta"
name[0]
#space is character
name[1] = a
name[4]=t
name[-1] = a
name[-2]=t



't'

In [11]:
#slicing
#start:end(3 is not inclusive) 0-1-2

name [0:3] 

name [1:2]


NameError: name 'name' is not defined

In [6]:
ord('A')


65

In [7]:
data = "this is string , lets learn it"
len(data)


30

In [8]:
data.lower()


'this is string , lets learn it'

In [9]:
data.upper()


'THIS IS STRING , LETS LEARN IT'

In [12]:
data= "hi mam"
len(data)

6

In [13]:
data.upper()

'HI MAM'

In [15]:
name ="jones"
name[0]

'j'

In [16]:
name[-2]

'e'

In [17]:
name[2:-3]

''

In [18]:
# Python String Operations
str1 = 'Hello'
str2 =' World!'
str3=str1 + str2
# using +
#concatenation

print('str1 + str2 = ', str3)


str1 + str2 =  Hello World!


In [19]:
# using *
#repeatition
print('str1 * 3 =', str1 * 5)


str1 * 3 = HelloHelloHelloHelloHello


In [20]:
for i in str3:
    print(i)


H
e
l
l
o
 
W
o
r
l
d
!


In [21]:
if 'Hello' in str1:
    print("present")
else:
    print("not present")


present


In [22]:
if 'hello' not in str1:
    print("not present")
else:
    print("present")


not present


In [23]:
str.capitalize("hello world")


'Hello world'

In [24]:
str1.find("l")


2

In [25]:
str1.replace("H","Y")


'Yello'

In [26]:
data = "this is string , lets learn it"
data.split(" ")


['this', 'is', 'string', ',', 'lets', 'learn', 'it']

In [27]:
for d in data:
    print(d)


t
h
i
s
 
i
s
 
s
t
r
i
n
g
 
,
 
l
e
t
s
 
l
e
a
r
n
 
i
t


In [28]:
l=0
for d in data:
    l=l+1
    
print(l)


30


In [29]:
l=0
for d in data:
    l=l+1
    
print(l)


30


In [30]:
len(data) #no of characters present in string


30

In [31]:
data= """Hi this is jones from trichy i have complete mechanical engineering and waorking as recuriter in one of the famous company,im earning as much as im satisfied and also im persuing data analyst from edubridge to get a knowledge about data analyst"""
data.split(" ")

['Hi',
 'this',
 'is',
 'jones',
 'from',
 'trichy',
 'i',
 'have',
 'complete',
 'mechanical',
 'engineering',
 'and',
 'waorking',
 'as',
 'recuriter',
 'in',
 'one',
 'of',
 'the',
 'famous',
 'company,im',
 'earning',
 'as',
 'much',
 'as',
 'im',
 'satisfied',
 'and',
 'also',
 'im',
 'persuing',
 'data',
 'analyst',
 'from',
 'edubridge',
 'to',
 'get',
 'a',
 'knowledge',
 'about',
 'data',
 'analyst']

In [32]:
for d in data:
    print(d)
    

H
i
 
t
h
i
s
 
i
s
 
j
o
n
e
s
 
f
r
o
m
 
t
r
i
c
h
y
 
i
 
h
a
v
e
 
c
o
m
p
l
e
t
e
 
m
e
c
h
a
n
i
c
a
l
 
e
n
g
i
n
e
e
r
i
n
g
 
a
n
d
 
w
a
o
r
k
i
n
g
 
a
s
 
r
e
c
u
r
i
t
e
r
 
i
n
 
o
n
e
 
o
f
 
t
h
e
 
f
a
m
o
u
s
 
c
o
m
p
a
n
y
,
i
m
 
e
a
r
n
i
n
g
 
a
s
 
m
u
c
h
 
a
s
 
i
m
 
s
a
t
i
s
f
i
e
d
 
a
n
d
 
a
l
s
o
 
i
m
 
p
e
r
s
u
i
n
g
 
d
a
t
a
 
a
n
a
l
y
s
t
 
f
r
o
m
 
e
d
u
b
r
i
d
g
e
 
t
o
 
g
e
t
 
a
 
k
n
o
w
l
e
d
g
e
 
a
b
o
u
t
 
d
a
t
a
 
a
n
a
l
y
s
t


In [33]:
l=0
for d in data:
    l=l+1
    
print(l)

244


In [34]:
len(data)

244

In [38]:
data[24:-33]

'ichy i have complete mechanical engineering and waorking as recuriter in one of the famous company,im earning as much as im satisfied and also im persuing data analyst from edubridge to g'

In [39]:
newstr='''this is one line.
this is second line.
This is third line.'''

lines=newstr.split('\n')
print(lines)


['this is one line.', 'this is second line.', 'This is third line.']


In [40]:
count=0
for i in lines:
    count=count+1
    
print(count)


3


In [41]:
newstr.title()


'This Is One Line.\nThis Is Second Line.\nThis Is Third Line.'

In [42]:
newstr.capitalize()


'This is one line.\nthis is second line.\nthis is third line.'

In [43]:
newstr.upper()


'THIS IS ONE LINE.\nTHIS IS SECOND LINE.\nTHIS IS THIRD LINE.'

In [44]:
newstr.lower()


'this is one line.\nthis is second line.\nthis is third line.'

In [45]:
new2=newstr.replace("t","T")
print(new2)


This is one line.
This is second line.
This is Third line.


In [46]:
new2.replace('T','I')


'Ihis is one line.\nIhis is second line.\nIhis is Ihird line.'

In [47]:
data= """In computer programming, a string is traditionally a sequence of characters, either as a literal constant or as some kind of variable. The latter may allow its elements to be mutated and the length changed, or it may be fixed (after creation). A string is generally considered as a data type and is often implemented as an array data structure of bytes (or words) that stores a sequence of elements, typically characters, using some character encoding. String may also denote more general arrays or other sequence (or list) data types and structures.
Depending on the programming language and precise data type used, a variable declared to be a string may either cause storage in memory to be statically allocated for a predetermined maximum length or employ dynamic allocation to allow it to hold a variable number of elements.
"""
len(data)

829

In [51]:
data= """In computer programming, a string is traditionally a sequence of characters, either as a literal constant or as some kind of variable. The latter may allow its elements to be mutated and the length changed, or it may be fixed (after creation). A string is generally considered as a data type and is often implemented as an array data structure of bytes (or words) that stores a sequence of elements, typically characters, using some character encoding. String may also denote more general arrays or other sequence (or list) data types and structures.
Depending on the programming language and precise data type used, a variable declared to be a string may either cause storage in memory to be statically allocated for a predetermined maximum length or employ dynamic allocation to allow it to hold a variable number of elements.
"""
data.replace("string","STRING")

'In computer programming, a STRING is traditionally a sequence of characters, either as a literal constant or as some kind of variable. The latter may allow its elements to be mutated and the length changed, or it may be fixed (after creation). A STRING is generally considered as a data type and is often implemented as an array data structure of bytes (or words) that stores a sequence of elements, typically characters, using some character encoding. String may also denote more general arrays or other sequence (or list) data types and structures.\nDepending on the programming language and precise data type used, a variable declared to be a STRING may either cause storage in memory to be statically allocated for a predetermined maximum length or employ dynamic allocation to allow it to hold a variable number of elements.\n'

In [52]:
data= """In computer programming, a string is traditionally a sequence of characters, either as a literal constant or as some kind of variable. The latter may allow its elements to be mutated and the length changed, or it may be fixed (after creation). A string is generally considered as a data type and is often implemented as an array data structure of bytes (or words) that stores a sequence of elements, typically characters, using some character encoding. String may also denote more general arrays or other sequence (or list) data types and structures.
Depending on the programming language and precise data type used, a variable declared to be a string may either cause storage in memory to be statically allocated for a predetermined maximum length or employ dynamic allocation to allow it to hold a variable number of elements.
"""
data. split()

['In',
 'computer',
 'programming,',
 'a',
 'string',
 'is',
 'traditionally',
 'a',
 'sequence',
 'of',
 'characters,',
 'either',
 'as',
 'a',
 'literal',
 'constant',
 'or',
 'as',
 'some',
 'kind',
 'of',
 'variable.',
 'The',
 'latter',
 'may',
 'allow',
 'its',
 'elements',
 'to',
 'be',
 'mutated',
 'and',
 'the',
 'length',
 'changed,',
 'or',
 'it',
 'may',
 'be',
 'fixed',
 '(after',
 'creation).',
 'A',
 'string',
 'is',
 'generally',
 'considered',
 'as',
 'a',
 'data',
 'type',
 'and',
 'is',
 'often',
 'implemented',
 'as',
 'an',
 'array',
 'data',
 'structure',
 'of',
 'bytes',
 '(or',
 'words)',
 'that',
 'stores',
 'a',
 'sequence',
 'of',
 'elements,',
 'typically',
 'characters,',
 'using',
 'some',
 'character',
 'encoding.',
 'String',
 'may',
 'also',
 'denote',
 'more',
 'general',
 'arrays',
 'or',
 'other',
 'sequence',
 '(or',
 'list)',
 'data',
 'types',
 'and',
 'structures.',
 'Depending',
 'on',
 'the',
 'programming',
 'language',
 'and',
 'precise',
 'd

In [53]:
data= """In computer programming, a string is traditionally a sequence of characters, either as a literal constant or as some kind of variable. The latter may allow its elements to be mutated and the length changed, or it may be fixed (after creation). A string is generally considered as a data type and is often implemented as an array data structure of bytes (or words) that stores a sequence of elements, typically characters, using some character encoding. String may also denote more general arrays or other sequence (or list) data types and structures.
Depending on the programming language and precise data type used, a variable declared to be a string may either cause storage in memory to be statically allocated for a predetermined maximum length or employ dynamic allocation to allow it to hold a variable number of elements.
"""
data.replace("string","string in python")

'In computer programming, a string in python is traditionally a sequence of characters, either as a literal constant or as some kind of variable. The latter may allow its elements to be mutated and the length changed, or it may be fixed (after creation). A string in python is generally considered as a data type and is often implemented as an array data structure of bytes (or words) that stores a sequence of elements, typically characters, using some character encoding. String may also denote more general arrays or other sequence (or list) data types and structures.\nDepending on the programming language and precise data type used, a variable declared to be a string in python may either cause storage in memory to be statically allocated for a predetermined maximum length or employ dynamic allocation to allow it to hold a variable number of elements.\n'

In [54]:
data= """In computer programming, a string is traditionally a sequence of characters, either as a literal constant or as some kind of variable. The latter may allow its elements to be mutated and the length changed, or it may be fixed (after creation). A string is generally considered as a data type and is often implemented as an array data structure of bytes (or words) that stores a sequence of elements, typically characters, using some character encoding. String may also denote more general arrays or other sequence (or list) data types and structures.
Depending on the programming language and precise data type used, a variable declared to be a string may either cause storage in memory to be statically allocated for a predetermined maximum length or employ dynamic allocation to allow it to hold a variable number of elements.
"""
data.replace("s","p")

'In computer programming, a ptring ip traditionally a pequence of characterp, either ap a literal conptant or ap pome kind of variable. The latter may allow itp elementp to be mutated and the length changed, or it may be fixed (after creation). A ptring ip generally conpidered ap a data type and ip often implemented ap an array data ptructure of bytep (or wordp) that ptorep a pequence of elementp, typically characterp, uping pome character encoding. String may alpo denote more general arrayp or other pequence (or lipt) data typep and ptructurep.\nDepending on the programming language and precipe data type uped, a variable declared to be a ptring may either caupe ptorage in memory to be ptatically allocated for a predetermined maximum length or employ dynamic allocation to allow it to hold a variable number of elementp.\n'

In [10]:
#username and password
print("Kindly Enter Your Username And Password")
count = 0
while count<3:
    username = input("Enter Your Username: ")
    password = input("Enter Your Password: ")
    if username=='shreya' and password=='Shreya@25':
        print("Access Granted!")
        break
    else:
        print("Access Denied. Sorry, Try again.")
    count = count+1


Kindly Enter Your Username And Password
Enter Your Username: shreya
Enter Your Password: dsfgb
Access Denied. Sorry, Try again.
Enter Your Username: shreya
Enter Your Password: Shreya@25
Access Granted!


In [11]:
empty = [] #creation of empty list


In [12]:
num_list = [1,2,3,4,5] #numeric data
char_list = ["abc","xyz","pqr","ijk"] #character/string data
com_list=["abc",123,6.99,True] #hybrid/mixed data


In [13]:
print(num_list)
print(char_list)
print(com_list)


[1, 2, 3, 4, 5]
['abc', 'xyz', 'pqr', 'ijk']
['abc', 123, 6.99, True]


In [14]:
com_list [1:3] #start 1: end 2(end value not inclusive)


[123, 6.99]

In [15]:
com_list [:]

['abc', 123, 6.99, True]

In [16]:
com_list [1:]

[123, 6.99, True]

In [17]:
char_list [2:4]

['pqr', 'ijk']

In [18]:
len(com_list)

4

In [19]:
items = ['idily','dosa','pongal','briyani','barbeque']


In [3]:
items = ['idily','dosa','pongal','briyani','barbeque']

items[2]='vadai'

In [46]:
items = ['idily','dosa','pongal','briyani','barbeque']
items.append("pizza")


In [7]:
items = ['idily','dosa','pongal','briyani','barbeque']
items [-1:]

['barbeque']

In [11]:
char_list = ["abc","xyz","pqr","ijk"]



In [14]:
char_list = ["abc","xyz","pqr","ijk"]
char_list[2:0:-1]


['pqr', 'xyz']

In [16]:
char_list[::-1]#reverse a string

['ijk', 'pqr', 'xyz', 'abc']

In [18]:
new_items=["veg nudgets","french fries"]
items.append(new_items)
items

['idily',
 'dosa',
 'pongal',
 'briyani',
 'barbeque',
 ['veg nudgets', 'french fries'],
 ['veg nudgets', 'french fries']]

In [19]:
list3=new_items + ["idali sambar","dosa"] #concatenation
list3


['veg nudgets', 'french fries', 'idali sambar', 'dosa']

In [20]:
#index
#append single
#append directly list
#append list variable
#concatenation +


In [24]:
items1=["apple","orange","grapes"]
items2=["carrot","potato","cabbage"]
items1.append(items2)
print(items1)

['apple', 'orange', 'grapes', ['carrot', 'potato', 'cabbage']]


In [30]:
items1=["apple","orange","grapes"]
items1.remove("grapes")
items1

['apple', 'orange']

In [37]:
items1.pop(0)
items1

IndexError: pop from empty list

In [39]:
length=len(items)
length


7

In [41]:
print(i)

NameError: name 'i' is not defined

In [42]:
firstnames=["anisley","ben","chani","depak"]
preferedsize=["small","large","medium"]

In [45]:
#1-add depak size
preferedsize=["small","large","medium"]
preferedsize.append("medium")
preferedsize

['small', 'large', 'medium', 'medium']

In [1]:
firstnames=["anisley","ben","chani","depak"]
preferedsize=["small","large","medium"]
firstnames.append(preferedsize)
print(firstnames)

['anisley', 'ben', 'chani', 'depak', ['small', 'large', 'medium']]


In [2]:
customer_data1= ["Ainsley","small","True"]
customer_data2= ["Ben","Large","False"]
customer_data3=["chani","Medium","true"]
customer_data4= ["depak","medium","False"]
customer_data= (customer_data1+customer_data2+customer_data3+customer_data4)
print(customer_data)


['Ainsley', 'small', 'True', 'Ben', 'Large', 'False', 'chani', 'Medium', 'true', 'depak', 'medium', 'False']


In [3]:
customer_data2.remove("Large")
customer_data2


['Ben', 'False']

In [4]:
customer_data_final= print(customer_data + (["Amit","Large","True"]) + (["Karim","X-Large","False"]))
customer_data_final


['Ainsley', 'small', 'True', 'Ben', 'Large', 'False', 'chani', 'Medium', 'true', 'depak', 'medium', 'False', 'Amit', 'Large', 'True', 'Karim', 'X-Large', 'False']


In [5]:
store_line = ["Kerala", "Tamilnadu", "Maharshtra", "Delhi"]
store_line.insert(2, "Uttarakhand")#location, value
print(store_line)


['Kerala', 'Tamilnadu', 'Uttarakhand', 'Maharshtra', 'Delhi']


In [6]:
#creating consecutive list using range()
#range(start,last index,step)
#range(0,10,2) 0 2 4 6 8 
my_range = range(1,10,2)#last value is not inclusive
print(list(my_range))


[1, 3, 5, 7, 9]


In [7]:
my_range=range(2,15,6)
print(list(my_range))

[2, 8, 14]


In [8]:
my_range=range(20,1,-2)
print(list(my_range))

[20, 18, 16, 14, 12, 10, 8, 6, 4, 2]


In [9]:
num=[1,2,3,4,5]

new_list=[]

for i in num:
    new_list.append(i**2)
    
new_list


[1, 4, 9, 16, 25]

In [10]:
num=[2,4,6,8]
new_list=[]

for i in num:
    new_list.append(i**3)
    
new_list


[8, 64, 216, 512]

In [11]:
new_list.count(216)


1

In [12]:
name=["trichy","chennai","coimbatore","erode","thanjore"]
for i in name:
    print(len(i))#string, each element of list, no of characters present in each item of list
    
print("length of list",len(name)) #total number of element present in list


6
7
10
5
8
length of list 5


In [14]:
i=0
while i<len(name):
    print(name[i])
    i=i+1
print("length of list",len(name))

trichy
chennai
coimbatore
erode
thanjore
length of list 5


In [15]:
#calculate cube of each element of list l1=[2,4,6,8,10]
#store length of each element in list2 for each member of given list. country=["India","United states America","England","Dubai","Russia","China","Srilanka"]
#calculate sum of all numbers present in list. l=[10,20,26,56,89,67]
# list of salaries -> salary=[10000,20000,22000,34000,45000,49000] add 15% bonus to salaries less than 25k and store in another list called bonus_salary

In [16]:
#calculate cube of each element of list l1=[2,4,6,8,10]
num=[2,4,6,8,10]
new_list=[]

for i in num:
    new_list.append(i**3)
    
new_list


[8, 64, 216, 512, 1000]

In [17]:
#store length of each element in list2 for each member of given list. country=["India","United states America","England","Dubai","Russia","China","Srilanka"]
country=["India","United states America","England","Dubai","Russia","China","Srilanka"]
for i in country:
    print(len(i))
print("length of list",len(country))
    

5
21
7
5
6
5
8
length of list 7


In [20]:
#calculate sum of all numbers present in list. l=[10,20,26,56,89,67]
l=[10,20,26,56,89,67]
i=0
sum=0
while i<len(l):
    sum=sum+l[i]
    i=i+1
    
print(sum)


268


In [21]:
# list of salaries -> salary=[10000,20000,22000,34000,45000,49000] add 15% bonus to salaries less than 25k and store in another list called bonus_salary
salary=[10000,20000,22000,34000,45000,49000]
i=0
newsal=0
bonus=[]

while i< len(salary):
    if salary[i] < 25000:
        newsal=salary[i]+(salary[i]*0.15)
        bonus.append(newsal)
    i=i+1
        
print(bonus)


[11500.0, 23000.0, 25300.0]


In [4]:
#Your computer is the doorman at a voting booth in a country where the voting age is 21.Loop through the ages list.
#If an entry is less than 21, skip it and move to the next entry. Otherwise, print() the age.
ages=[21,32,45,18,19,20,22,34,16]
for i in ages:
    if i<21:
        continue
    else:
        print(i)


21
32
45
22
34


In [ ]:
List of list
#lol

In [6]:
lol=[["Jones","Naveen"],["ajith","Aaron"],["Tasneem","Riji"]]
print(lol)


[['Jones', 'Naveen'], ['ajith', 'Aaron'], ['Tasneem', 'Riji']]


In [8]:
lol[0]

['Jones', 'Naveen']

In [10]:
lol[2]

['Tasneem', 'Riji']

In [12]:
lol[2][0]


'Tasneem'

In [13]:
for sublist in lol:
    for name in sublist:
        print(name)


Jones
Naveen
ajith
Aaron
Tasneem
Riji


In [14]:
items_on_sale = ["blue shirt", "jeans","striped socks", "knit dress", "red headband"]
key = "jeans"
for i in items_on_sale:
    if key==i:
    print("present")
    break
    else:
    print("not present")


IndentationError: expected an indented block (2355816441.py, line 5)

In [15]:
items_on_sale = ["blue shirt", "jeans","striped socks", "knit dress", "red headband"]
key = "blue shirt"
flag=0

for i in items_on_sale:
    if key==i:
        flag=1
        
        
if flag==1:
    print("present")
else:
    print("not present")


present


In [16]:
#list of covid patients for second wave in a one day at different cities is given 
#add new element for city hyderabad with number of patient 20000
#updated count for mumbai is 42000 , update that in ur list
#insert new entry for nagpur with number of patients 5000 in given list
#calculate total numbers of patients in given list

new_variant=[['pune',20000],['mumbai',36000],['lukhnaw',15000],['banglore',12000],['cochin',25000]]


In [19]:
#add new element for city hyderabad with number of patient 20000
new_variant=[['pune',20000],['mumbai',36000],['lukhnaw',15000],['banglore',12000],['cochin',25000]]
new_variant.append(['hyderabad',20000])
new_variant

[['pune', 20000],
 ['mumbai', 36000],
 ['lukhnaw', 15000],
 ['banglore', 12000],
 ['cochin', 25000],
 ['hyderabad', 20000]]

In [23]:
#updated count for mumbai is 42000 , update that in ur list
new_variant=[['pune',20000],['mumbai',36000],['lukhnaw',15000],['banglore',12000],['cochin',25000]]
replaced_new_variant = new_variant.replace('36000', '42000')
print(replaced_text)

AttributeError: 'list' object has no attribute 'replace'

In [21]:
#insert new entry for nagpur with number of patients 5000 in given list
new_variant=[['pune',20000],['mumbai',36000],['lukhnaw',15000],['banglore',12000],['cochin',25000]]
new_variant.append(['nagpur',5000])
new_variant

[['pune', 20000],
 ['mumbai', 36000],
 ['lukhnaw', 15000],
 ['banglore', 12000],
 ['cochin', 25000],
 ['nagpur', 5000]]

In [29]:
#calculate total numbers of patients in given list
new_variant=[['pune', 20000],['lukhnaw', 15000],['banglore', 12000],['cochin', 25000],['nagpur', 5000]]
sum=new_variant[0][1]+new_variant[1][1]+new_variant[2][1]+new_variant[3][1]+new_variant[4][1]
print(sum)

77000


In [3]:
new_variant=[['pune', 20000],['lukhnaw', 15000],['banglore', 12000],['cochin', 25000],['nagpur', 5000]]
i=0
total=0
while i<len(new_variant):
    total=total+new_variant[i][1]
    i+=1
print(total)

77000


In [4]:
list3=[[1,"akshay",76],[2,"deepam",56],[3,"anjali",89],[4,"narayani",88],[5,"vyom",90],[6,"Hrudaya",82]]
#[[roll,name,marks]]

#vyom
#index to access hrudays marks
#index to get roll number of anjali
#total marks


In [6]:
#vyom
list3=[[1,"akshay",76],[2,"deepam",56],[3,"anjali",89],[4,"narayani",88],[5,"vyom",90],[6,"Hrudaya",82]]
list3[4]

[5, 'vyom', 90]

In [13]:
list3=[[1,"akshay",76],[2,"deepam",56],[3,"anjali",89],[4,"narayani",88],[5,"vyom",90],[6,"Hrudaya",82]]
list3[5][2]

82

In [33]:
#index to get roll number of anjali
list3[2][0]

3

In [32]:
#total marks
list3=[[1,"akshay",76],[2,"deepam",56],[3,"anjali",89],[4,"narayani",88],[5,"vyom",90],[6,"Hrudaya",82]]
sum=list3[0][2]+list3[1][2]+list3[2][2]+list3[3][2]+list3[4][2]+list3[5][2]
print(sum)

481


In [1]:
#loop 
#repeat

i=range(10)
print(i)
print(type(i))


range(0, 10)
<class 'range'>


# LOOPING

In [15]:
for i in range(1,21):
    print(i,end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 

In [16]:
#odd Numbers
for i in range(0,12,3):
    print(i)


0
3
6
9


In [18]:
#even numbers
for i in range(1,16):
    if i%2==0:
        print(i,end=" ")


2 4 6 8 10 12 14 

In [5]:
sum=0
for i in range(1,11):
    sum=sum+i
print(sum)


55


In [6]:
for i in range(7,71,7):
    print(i,end=" ")


7 14 21 28 35 42 49 56 63 70 

In [7]:
for i in range(20,1,-2):
    print(i,end=" ")


20 18 16 14 12 10 8 6 4 2 

In [8]:
str_new="this is my fav sentence"
str_new[0]


't'

In [9]:
str_new[1]


'h'

In [10]:
str_new[2]


'i'

In [11]:
len(str_new)


23

In [12]:
for i in str_new:
    print(i,end=" ")


t h i s   i s   m y   f a v   s e n t e n c e 

In [13]:
for i in range(len(str_new)):
    if i%2==0:
        print(str_new[i])


t
i
 
s
m
 
a
 
e
t
n
e


In [19]:
l2=[["shivam","sonali"],["sayali","ashwini","ajith"],["riji","tasneema","hepsy"],["Jones","faizan","yashwanth","usman"]]



In [20]:
len(l2)


4

In [21]:
l2[0].extend(["Kaviya"])
l2


[['shivam', 'sonali', 'Kaviya'],
 ['sayali', 'ashwini', 'ajith'],
 ['riji', 'tasneema', 'hepsy'],
 ['Jones', 'faizan', 'yashwanth', 'usman']]

In [22]:
l2[0].append("kaviya")
l2


[['shivam', 'sonali', 'Kaviya', 'kaviya'],
 ['sayali', 'ashwini', 'ajith'],
 ['riji', 'tasneema', 'hepsy'],
 ['Jones', 'faizan', 'yashwanth', 'usman']]

In [23]:
l2[1].append(["aarthy","anas"])
l2


[['shivam', 'sonali', 'Kaviya', 'kaviya'],
 ['sayali', 'ashwini', 'ajith', ['aarthy', 'anas']],
 ['riji', 'tasneema', 'hepsy'],
 ['Jones', 'faizan', 'yashwanth', 'usman']]

In [24]:
l2[2].extend(["avinash","naveen"])
l2


[['shivam', 'sonali', 'Kaviya', 'kaviya'],
 ['sayali', 'ashwini', 'ajith', ['aarthy', 'anas']],
 ['riji', 'tasneema', 'hepsy', 'avinash', 'naveen'],
 ['Jones', 'faizan', 'yashwanth', 'usman']]

In [25]:
l2[1]


['sayali', 'ashwini', 'ajith', ['aarthy', 'anas']]

In [26]:
l2[3][0]


'Jones'

In [27]:
l2[1][3][0]


'aarthy'

In [28]:
l2[1][3].insert(1,"Aaron")


In [29]:
l2


[['shivam', 'sonali', 'Kaviya', 'kaviya'],
 ['sayali', 'ashwini', 'ajith', ['aarthy', 'Aaron', 'anas']],
 ['riji', 'tasneema', 'hepsy', 'avinash', 'naveen'],
 ['Jones', 'faizan', 'yashwanth', 'usman']]

In [1]:
l=[1,2,3,4,5,6]
l2=[]
for i in l:
    l2.append(i**2)
    
print(l2)


[1, 4, 9, 16, 25, 36]


In [2]:
l=[1,2,3,4,5,6]
l3 = [i**2 for i in l]
print(l3)


[1, 4, 9, 16, 25, 36]


In [3]:
l4=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
l5 = [i**2 for i in l4 if i%2!=0]
l5


[1, 9, 25, 49, 81, 121, 169, 225]

In [4]:
#list comprehension
#[<expression> <for loop><conditon>]


In [7]:
salary = [5000,10000,12000,13000,17000,20000,25000,45000]
bonus_sal=[i+5000 for i in salary if i<10000]
bonus_sal


[10000]

In [28]:
#CAPITAL LETTER
fruits=["apple", "banana", "cherry", "kiwi", "mango"]
cap_fruits=[i.upper() for i in fruits]
print(cap_fruits)

['APPLE', 'BANANA', 'CHERRY', 'KIWI', 'MANGO']


In [30]:
#length
fruits=["apple", "banana", "cherry", "kiwi", "mango"]
cap_fruits=[len(i) for i in fruits]
print(cap_fruits)

[5, 6, 6, 4, 5]


In [37]:
#[<True expression> if<condition> else <false> <for loop> ]

newlist4 = ["xyz" if x == "banana" else "orange" for x in fruits]
print(newlist4)


['orange', 'xyz', 'orange', 'orange', 'orange']


In [39]:
numbers = [2, -1, 79, 33, -45]
newlist4 = [if x==0 else x%%0 for x in numbers]
print(newlist4)


SyntaxError: invalid syntax (138669457.py, line 2)

# DICTIONARY

In [40]:
#" ": strings
#[]:list
#{ }: dictionary


In [42]:
dict1 = {}


In [43]:
type(dict1)


dict

In [44]:
#{key:value}

dict2 ={1:"apple",2:"banana",3:"cherry",4:"Dates",5:"pineapple"}
print(dict2)


{1: 'apple', 2: 'banana', 3: 'cherry', 4: 'Dates', 5: 'pineapple'}


In [45]:
dict2[1]


'apple'

In [46]:
dict2[5]


'pineapple'

In [47]:
dict2.keys()


dict_keys([1, 2, 3, 4, 5])

In [48]:
dict2.values()


dict_values(['apple', 'banana', 'cherry', 'Dates', 'pineapple'])

In [49]:
dict2.items()


dict_items([(1, 'apple'), (2, 'banana'), (3, 'cherry'), (4, 'Dates'), (5, 'pineapple')])

In [50]:
dict3={
    1:"Delhi",
    'two':100,
    3: True,
    "four":[1,2,3,4]
}
dict3


{1: 'Delhi', 'two': 100, 3: True, 'four': [1, 2, 3, 4]}

In [51]:
dict3["four"]


[1, 2, 3, 4]

In [52]:
dict3[3]


True

In [53]:
#dictionary["key"]=value


In [55]:
dict3["four"]

[1, 2, 3, 4]

In [56]:
shapes={1:"rectangle",2:"triangle",3:"circle"}
print(shapes)


{1: 'rectangle', 2: 'triangle', 3: 'circle'}


In [57]:
#adding values []
#dict[new_key]= value
shapes[4]="hexagon"
shapes[5]="polygon"

print(shapes)


{1: 'rectangle', 2: 'triangle', 3: 'circle', 4: 'hexagon', 5: 'polygon'}


In [58]:
#adding values []
#dict[new_key]= value
shapes[4]="hexagon"
shapes[5]="polygon"

print(shapes)
print(shapes)


{1: 'rectangle', 2: 'triangle', 3: 'circle', 4: 'hexagon', 5: 'polygon'}
{1: 'rectangle', 2: 'triangle', 3: 'circle', 4: 'hexagon', 5: 'polygon'}


In [59]:
#adding multiple values to dictionary
shape2 = {6:"right angle triangle",7:"rhombus"}
shapes.update(shape2)
print(shapes)


{1: 'rectangle', 2: 'triangle', 3: 'circle', 4: 'hexagon', 5: 'polygon', 6: 'right angle triangle', 7: 'rhombus'}


In [60]:
#get command
#accesing particular element
print(shape2.get(6))


right angle triangle


In [61]:
len(shapes)#length of dictionary


7

In [62]:
print(shapes.get(8))


None


In [63]:
print(shapes.get(5,"key not present"))


polygon


In [64]:
print(shapes.get(10,"key not present"))


key not present


In [65]:
shapes[8]


KeyError: 8

In [67]:
print(shapes.get(8,"hello world"))

hello world


In [68]:
#by using pop it ommits
shapes.pop(6)
shapes


{1: 'rectangle',
 2: 'triangle',
 3: 'circle',
 4: 'hexagon',
 5: 'polygon',
 7: 'rhombus'}

In [69]:
shapes.pop(2)
shapes

{1: 'rectangle', 3: 'circle', 4: 'hexagon', 5: 'polygon', 7: 'rhombus'}

In [77]:
shapes.pop(3)
shapes

KeyError: 3

In [78]:
for i in shapes:
    print(i)


1
4
7


In [79]:
for i in shapes:
    print(shapes[i])


rectangle
hexagon
rhombus


In [80]:
for i in shapes.values():
    print(i)


rectangle
hexagon
rhombus


In [81]:
del shapes[2]
shapes


KeyError: 2

In [82]:
for i in shapes.values():
    print(i.upper())


RECTANGLE
HEXAGON
RHOMBUS


In [83]:
for i in shapes.values():
    print(len(i))


9
7
7


In [84]:
for i in shapes.keys():
    if i%2==0:
        print(shapes[i])


hexagon


In [85]:
#dictionary[key]=value


In [95]:
sample_dict = {'a': 100, 'b': 200, 'c': 300}
i=0
if i=200==0
print(yes)
else

break

SyntaxError: invalid syntax (2515713666.py, line 3)

In [91]:
sample_dict = {
  "name": "Kelly",
  "age":25,
  "salary": 8000,
  "city": "New york"
}


In [97]:
dict_new={1:100,2:345,3:678,4:789,5:786,6:999}
values = dict_new.values()
total_value = sum(values)
print(total_value)

3697


In [1]:
shape3={1: 'rectangle', 2: 'triangle', 3: 'circle', 4: 'hexagon', 5: 'polygon', 6: 'right angle triangle', 7: 'rhombus'}
shape3


{1: 'rectangle',
 2: 'triangle',
 3: 'circle',
 4: 'hexagon',
 5: 'polygon',
 6: 'right angle triangle',
 7: 'rhombus'}

In [2]:
for k,v in shape3.items():
    print(k,v)
    
    
print(type(k))
print(type(v))


1 rectangle
2 triangle
3 circle
4 hexagon
5 polygon
6 right angle triangle
7 rhombus
<class 'int'>
<class 'str'>


In [3]:
#Dictionary comprehension
#newdict={expression (k:v) for k,v in dict.items()}
compdict={k:v for k,v in shape3.items()}
compdict


{1: 'rectangle',
 2: 'triangle',
 3: 'circle',
 4: 'hexagon',
 5: 'polygon',
 6: 'right angle triangle',
 7: 'rhombus'}

In [4]:
compdict={k:v.upper() for k,v in shape3.items()}
compdict


{1: 'RECTANGLE',
 2: 'TRIANGLE',
 3: 'CIRCLE',
 4: 'HEXAGON',
 5: 'POLYGON',
 6: 'RIGHT ANGLE TRIANGLE',
 7: 'RHOMBUS'}

In [5]:
#Expected output :{0: 0, 2: 4, 4: 16, 6: 36, 8: 64, 10: 100}
#keys are even numbers
#values are square of keys

numbers=[0,1,2,3,4,5,6,7,8,9,10]
numbers


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [6]:
#dict[key]=value
exp_dict={}
for i in numbers:
    if i%2==0:
        exp_dict[i]=i**2
    i=i+1
    
print(exp_dict)


{0: 0, 2: 4, 4: 16, 6: 36, 8: 64, 10: 100}


In [7]:
#{key:value for k in list <condition>}
new_dic={k:k**2 for k in numbers if k%2==0}
new_dic


{0: 0, 2: 4, 4: 16, 6: 36, 8: 64, 10: 100}

In [19]:
a=["book","data science","data analytics","dictionary"]
len(a)

4

In [22]:
a=["book","data science","data analytics","dictionary"]
a_new={k:len(k) for k in a}
a_new

{'book': 4, 'data science': 12, 'data analytics': 14, 'dictionary': 10}

In [33]:
a=["book","data science","data analytics","dictionary"]
a={k.upper():len(k) for k in a}
a_new

{'book': 4, 'data science': 12, 'data analytics': 14, 'dictionary': 10}

In [31]:
#create new dict for managers only
employee={1:"technician",2:"HR",3:"manager",4:"manager",5:"developer"}  
manager_dict={k:v for k,v in employee.items() if v=="manager"}
manager_dict


{3: 'manager', 4: 'manager'}

In [34]:
#merging or zip
food=['pizza','tea','dosa']
calories=[350,75,170]


In [35]:
single=zip(food,calories)
print(type(single))
print(single)


<class 'zip'>


In [36]:
food_dic={k:v for k,v in single}
food_dic


{'pizza': 350, 'tea': 75, 'dosa': 170}

In [40]:
drinks = ["espresso", "chai", "decaf", "drip"]
caffeine = [64, 40, 0, 120]
single=zip(drinks,caffeine)
print(type(single))
print(single)

<class 'zip'>


In [42]:
drinks_dic={k:v for k,v in single}
drinks_dic

{}

In [43]:
student = ["ajay","vijay","akash","vyom"]
marks = [78,89,90,67]
single=zip(student,marks)
print(type(single))
print(single)

<class 'zip'>


In [45]:
student_dic={k:v for k,v in single}
student_dic

{}

In [2]:
list2 = [1,2,2,3,1,4,5,1,2,6]
temp = []
for i in list2:
    if i not in temp:
        temp.append(i)
print(list(temp))


[1, 2, 3, 4, 5, 6]


In [3]:
a=set(list2)
a


{1, 2, 3, 4, 5, 6}

# SET


In [4]:
#two ways to create set
#1. using set()
#2. assigning values in {}


In [5]:
a={1,2,3,4,5}
type(a)


set

In [6]:
c={}#dictionary
b=set() #to create empty set
print(type(b))
print(type(c))


<class 'set'>
<class 'dict'>


In [7]:
A={1,2,3,4,5,6,7,8,9,10}
A.add(20)
A


{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 20}

In [8]:
len(A)


11

In [9]:
b=A.copy()
b


{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 20}

In [10]:
A.update({45,90,89})
A


{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 20, 45, 89, 90}

In [16]:
A.remove(45)
A

KeyError: 45

In [18]:
A.pop()
A

{3, 4, 5, 6, 7, 8, 9, 10, 20, 89, 90}

In [5]:
A.discard(90)
A

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

In [2]:
A={1,2,3,4,5,6,7,8,9,10}


In [3]:
A.replace("8","6")
A

AttributeError: 'set' object has no attribute 'replace'

# set of operations


In [6]:
a = {1,2,3,4,5}
b = {4,5,6,7,8}
uni = a.union(b)
print(uni)


{1, 2, 3, 4, 5, 6, 7, 8}


In [7]:
uni2=a|b #(a union b)
uni2


{1, 2, 3, 4, 5, 6, 7, 8}

In [8]:
intr=a.intersection(b)
intr


{4, 5}

In [9]:
intr2=a&b #a intersection b
intr2


{4, 5}

In [10]:
a = {1,2,3,4,5}
b = {4,5,6,7,8}
c=a-b #elements present in a but not in b 
c


{1, 2, 3}

In [11]:
c=b-a #elements present in b but not in a
c


{6, 7, 8}

In [12]:
diff=a.difference(b)
diff


{1, 2, 3}

In [13]:
diff2=b.difference(a)
diff2


{6, 7, 8}

In [14]:
a.symmetric_difference_update(b)
print(a)


{1, 2, 3, 6, 7, 8}


In [15]:
n={10,20,99,12,4,56}
print(max(n))
print(min(n))


99
4


In [16]:
p={10,89,77,25}


In [17]:
n.difference_update(p) #elements in n not in p, result stored back in n
n


{4, 12, 20, 56, 99}

In [18]:
p.clear()
p


set()

In [20]:
add() Adds an element to the set clear() Removes all the elements from the set copy() Returns a copy of the set difference() Returns a set containing the difference between two or more sets difference_update() Removes the items in this set that are also included in another, specified set discard() Remove the specified item
intersection() Returns a set, that is the intersection of two or more sets intersection_update() Removes the items in this set that are not present in other, specified set(s) isdisjoint() Returns whether two sets have a intersection or not issubset() Returns whether another set contains this set or not
issuperset() Returns whether this set contains another set or not pop() Removes an element from the set remove() Removes the specified element symmetric_difference() Returns a set with the symmetric differences of two sets symmetric_difference_update() inserts the symmetric differences from this set and another union() Return a set containing the union of sets update() Update the set with another set, or any other iterable


SyntaxError: invalid syntax (1164494073.py, line 1)

In [21]:
#identity operator
a=10
b=20
print(id(a))
print(id(b))

if ( a is b ):
    print (" both have same identity")
else:
    print ("both identities are different")

if ( id(a) == id(b) ):
    print("same ids")
else:
    print ("different ids")

if ( a is not b ):
    print (" different identity")
else:
    print ("same identities ")


3141378402896
3141378403216
both identities are different
different ids
 different identity


In [23]:
set1 = {2, 4, 5, 6}
set2 = {7, 8, 9, 10}
set3 = {1, 2}


In [24]:
print("set1 and set2 are disjoint?",set1.isdisjoint(set2))
 
print("set1 and set3 are disjoint?",set1.isdisjoint(set3))


set1 and set2 are disjoint? True
set1 and set3 are disjoint? False


In [25]:
x = {"a", "b", "c"}
y = {"f", "e", "d", "c", "b", "a"}

z = x.issubset(y)

print(z)


True


In [26]:
x = {"f", "e", "d", "c", "b", "a"}
y = {"a", "b", "c"}

z = x.issuperset(y)

print(z)


True


In [2]:
day={"mon","tue","wed","thu","fri"}
if "sat" in day:
    print("working")
else:
    print("holiday")


holiday


In [1]:
def function_sum():
""" information about function """
operaton/code
return value
function_sum()


IndentationError: expected an indented block (4259770923.py, line 2)

In [29]:
def function_sum():
""" information about function """
operaton/code
return value
function_sum()


IndentationError: expected an indented block (4259770923.py, line 2)

In [ ]:
#define function
def sum():
    a=int(input("enter number"))
    b=int(input("enter number"))
    c=a+b
    print(c)
    
sum() #function call


In [28]:
sum()


TypeError: sum() takes at least 1 positional argument (0 given)

In [3]:
def sum():
    a=int(input("24"))
    b=int(input("03"))
    c=a+b
    print(c)
sum()

2403
0324
27


In [5]:
def mul():
    A = int(input("enter a number"))
    B = int(input("enter a number"))
    C=A*B
    print(C)

mul()


enter a number24
enter a number03
72


In [6]:
def div():
    A = int(input("enter a number"))
    B = int(input("enter a number"))
    C=A%B
    print(C)

div()

enter a number24
enter a number12
0


In [1]:
def odd_even():
    A=int(input("enter the number"))
    if A%2==0:
        print("even number")
    else:
        print("odd number")
        
odd_even()

enter the number24
even number


In [1]:
Area = int(input("enter the radius of the circle: "))  
area_of_the_circle=22%7*R**2  
print ("The area of the given circle is: ", area_of_the_circle) 

enter the radius of the circle: 24


NameError: name 'R' is not defined

In [2]:
def add(n1,n2):
    sum=n1+n2
    print(sum)


In [3]:
add(10,20)


30


In [6]:
add(90,789)


879


In [8]:
#addition
def sum():
    a=int(input("enter a number"))
    b=int(input("enter a number"))
    c=a+b
    print(c)
sum()

enter a number12
enter a number24
36


In [9]:
#subraction
def sum():
    a=int(input("enter a number"))
    b=int(input("enter a number"))
    c=a-b
    print(c)
sum()

enter a number12
enter a number12
0


In [10]:
#multiplication
def sum():
    a=int(input("enter a number"))
    b=int(input("enter a number"))
    c=a*b
    print(c)
sum()

enter a number2
enter a number4
8


In [9]:
#division
def sum():
    a=int(input("enter a number"))
    b=int(input("enter a number"))
    c=a/b
    print(c)
sum()

enter a number12
enter a number24
0.5


In [12]:
def add(n1,n2):
    sum=n1+n2
    print(sum)

In [14]:
add(24,12)

36


In [17]:
def sub(n1,n2):
    sum=n1-n2
    print(sum)

In [18]:
sub(24,12)

12


In [19]:
def mul(n1,n2):
    sum=n1*n2
    print(sum)

In [21]:
mul(12,2)

24


In [22]:
def div(n1,n2):
    sum=n1*n2
    print(sum)

In [23]:
div(12,2)

24


In [24]:
def addition(a,b):#a,b parameters
    c=a+b
    print(c)
    
addition(3,4)#calling function with values called as arguments
addition(10,20)


7
30


In [25]:
def add(p,q):
    c=p+q
    return c #return is used to store in another variable

result=add(23,78)
print(result)


101


In [27]:
def add(p,q):
    return p+q

result=add(23,78)
print(result)


101


In [3]:
def jones_mp_func():
    print("jones mp")

In [4]:
jones_mp_func()

jones mp


In [5]:
def display(name):
    print("hello",name)
    
display ("jones")
    

hello jones


In [6]:
display(input("enter your name"))


enter your namejones
hello jones


In [7]:
n=input("enter name")
display(n)


enter namejones
hello jones


In [12]:
def add(a,b):
    return a+b
def sub(a,b):
    return a-b
def mul (a,b):
    return a/b

final= int(input("enter the choice"))

if final==1:
    result=add(6,6)
    print(result)
elif final==2:
    result=sub(6,6)
    print(result)
elif final==3:
    result=mul(6,6)
    print(result)
elif final==4:
    result=div(6,6)
    print(result)
else:
    print ("enter the choice")


enter the choice12
enter the choice


In [13]:
def user_in():
    a=int(input("enter number"))
    b=int(input("enter number"))
    ch=int(input("enter choice 1. Add 2. Sub 3.mul 4. div"))
    return a,b,ch

def add(x,y):
    return x+y

def sub(x,y):
    return x-y

def mul(x,y):
    return x*y

def div(x,y):
    return x/y

p,q,choice=user_in()

if choice==1:
    result=add(p,q)
elif choice==2:
    result=sub(p,q)
elif choice==3:
    result=p*q
elif choice==4:
    result=p/q
else:
    print("correct choice 1-4 ")
    
print("result =",result)


enter number12
enter number12
enter choice 1. Add 2. Sub 3.mul 4. div1
result = 24


In [14]:
#Create a function called generate_trip_instructions() that defines one parameter called location.

#generate_trip_instructions()Looks like you are planning a trip to visit <location>
#Where <location> will represent the location parameter.
 #generate_trip_instructions() should also let our users know they can reach their location using public transit.

#Let’s have generate_trip_instructions()also print out the following on a new line:

#You can use the public subway system to get to <location>
#Where <location> will represent the location parameter.
#Let’s have generate_trip_instructions()also print out the following on a new line:You can use the public subway system to get to <location>
#Where <location> will represent the location parameter.

#call the function and input the argument "Central Park", a backyard wonder in the heart of New York City.
#Change the argument to "Grand Central Station" and call the function again.

#What changed in the output?


In [15]:
def user_in():
    a=int(input("Banglore"))
    ch=int(input("enter choice 1. train 2. bus"))
    return a,b,

In [17]:
#types of arguments

def simple_interest(p,n,r=7.5):
    si=p*n*r/100
    print("simple interest:",si)
    

simple_interest(10000,5,10)#positional argument

simple_interest(n=3,p=20000,r=7)#keyword argument

simple_interest(10000,5)#default argument

simple interest: 5000.0
simple interest: 4200.0
simple interest: 3750.0


In [20]:
def areatriangle(l1=4,l2=8):
    area=1/2*l1*l2
    print("area of the triangle=",area)
    
areatriangle(l1=15,l2=20)
areatriangle(25)

area of the triangle= 150.0
area of the triangle= 100.0


In [1]:
def display_list(l):
    for i in l:
        if i%2==0:
            print(i)
            
            
display_list([1,2,3,4,54,6,7,8,9])


2
4
54
6
8


In [2]:
def list_fun(l):
    print("length of list",len(l))
    l.append(56)
    print(l)
    print(l[::-1])
    
list1=[10,20,30,40,50,60]   
list_fun(list1)


length of list 6
[10, 20, 30, 40, 50, 60, 56]
[56, 60, 50, 40, 30, 20, 10]


In [3]:
def bonus_sal(salary):
    bonus=[]
    for i in salary:
        bonus.append(i+i*0.2)
    return bonus
bonus=bonus_sal([10000,15000,45000,25000])
print(bonus)


[12000.0, 18000.0, 54000.0, 30000.0]


In [10]:
def str_opr(s):
    print("length of your string is ",len(s))
    print(s.upper())
    print(s.capitalize())
    print(s.split(" "))
    print(type(s))
    print(s.replace("a","n"))
    print(s.find("n"))
    
    
    
    for i in s:
        print(i)
    
str_opr("hello my name is anthony")


length of your string is  24
HELLO MY NAME IS ANTHONY
Hello my name is anthony
['hello', 'my', 'name', 'is', 'anthony']
<class 'str'>
hello my nnme is nnthony
9
h
e
l
l
o
 
m
y
 
n
a
m
e
 
i
s
 
a
n
t
h
o
n
y


In [5]:
def shut_down(dat):
    
    if dat== "yes":
        print("Shutting down")
    elif dat=="no":
        print("shutting aborted")
    else:
        print("Sorry")

shut_down("no")


shutting aborted


In [4]:
def trip_planner_welcome(name):
    print("welcome to tripplanner v1.0", name)
    
def estimated_time_rounded(estimated time):
    rounded_time = round (estimated time)
    return rounded_time





SyntaxError: invalid syntax (4196280631.py, line 4)

In [7]:
def taxi_fare():
    print("enter the destination", name)
    print("how much kms", name)
    price=[1000]
    i=0
    
    while i< len(price):
        

IndentationError: expected an indented block (2761870117.py, line 8)

In [8]:
name = input ("enter name:")
orgin= input ("enter orgin:")
destination1=input("enter destination:")
estimated_time= int(input("enter time:"))

trip_welcome(name)
destination(orgin,destination1,estimated_time)

enter name:jones
enter orgin:tamilnadu
enter destination:goa
enter time:8


NameError: name 'trip_welcome' is not defined

In [9]:
def cube(number):
     return number*number*number
def by_three(number):
    if number %3 ==0:
        return cube(number)
    else:
        return False

by_three(8)


False

In [10]:
def trip_planner_welcome(name):
    print("Welcome to tripplanner v1.0 ",name)
    
    
def destination_setup(origin,destination,estimated_time,mode_of_transport="car"):
    print("Your trip starts off in ",origin)
    print("you are travelling to ",destination)
    print("You will be travelling by ", mode_of_transport)
    print("It will take approximately "+str(estimated_time_rounded(estimated_time))+" hours")
    
def estimated_time_rounded(estimated_time):
    rounded_time = round(estimated_time)
    return rounded_time


name=input("enter name")
trip_planner_welcome(name)
destination_setup(input("enter your origin"),input("enter your destination"),float(input("enter estimated time")))


enter namejones
Welcome to tripplanner v1.0  jones
enter your origintamilnady
enter your destinationgoa
enter estimated time14.7
Your trip starts off in  tamilnady
you are travelling to  goa
You will be travelling by  car
It will take approximately 15 hours


In [11]:
def taxi_fare(source, destination,kms):#function definition
    fare = kms * 12
    print("your bill for travelling from " ,source ,"to ", destination ,"is" , fare)
    return fare

mybill = taxi_fare(input("enter source"),input("enter destination"),int(input("kms to travel"))) #function call


if mybill > 1000:#discount condition
    discountedbill = mybill - (mybill * 10/100)
    print("discounted bill is ",discountedbill)
else:
    print("no discount for nearby journeys")


enter sourcegoa
enter destinationtamilnadu
kms to travel1100
your bill for travelling from  goa to  tamilnadu is 13200
discounted bill is  11880.0


In [1]:
def Add(a,b):
    C=a+b
    return C
def Mul(a,b):
    D=a*b
    return D


In [3]:
import Cal
d=cal.Add(10,2)
m=cal.Mul(2,4)

print(d)
print(m)


ModuleNotFoundError: No module named 'Cal'

In [4]:
import factorial
f= factorial.fact(5)
print(f)


120


In [8]:
import add
a= add. sum(10,10)
print (a)

AttributeError: module 'add' has no attribute 'sum'

In [1]:
import simple
si= simple.Sim(10,10,10)
print(si)

10.0


In [4]:
with open("festival.txt") as fp:
    content=fp.read()
    print(content)


In [1]:
#to read data line by line
with open('festival.txt') as f2:
    first=f2.readline()
    print(first)
    sec=f2.readline()
    print(sec)
    third=f2.readline()
    print(third)
    fourth=f2.readline()
    print(fourth)
    five=f2.readline()
    print(five)


India is a big land of culture, we are united as indians.

we celerate christmas.

we celebrate easter.

we celebrate new year.

we celebrate ramzan.



In [2]:
with open("festival.txt") as f:
    lines=f.readlines()
    print(lines)


['India is a big land of culture, we are united as indians.\n', 'we celerate christmas.\n', 'we celebrate easter.\n', 'we celebrate new year.\n', 'we celebrate ramzan.\n', 'we celebrate diwali.']


In [5]:
with open("festival.txt") as f:
    count=f.readlines()
    print (count)

['India is a big land of culture, we are united as indians.\n', 'we celerate christmas.\n', 'we celebrate easter.\n', 'we celebrate new year.\n', 'we celebrate ramzan.\n', 'we celebrate diwali.']


In [6]:
with open("festival.txt") as f:
    type=f.readlines()
    print (type)

['India is a big land of culture, we are united as indians.\n', 'we celerate christmas.\n', 'we celebrate easter.\n', 'we celebrate new year.\n', 'we celebrate ramzan.\n', 'we celebrate diwali.']


In [1]:
with open("festival.txt") as f:
    type=f.readlines()
    print (type)

['India is a big land of culture, we are united as indians.\n', 'we celerate christmas.\n', 'we celebrate easter.\n', 'we celebrate new year.\n', 'we celebrate ramzan.\n', 'we celebrate diwali.']


In [1]:
with open("festival.txt","w") as wr:#over writes file contents
    wr.write("im overwriting a word......Google")

# CLASS


In [1]:
# creation of class
class Classname:
    variables
    def functions():
        body
        
#creation of object
obejctname = Classname()

#access
objectname.variable
objectname.function


NameError: name 'variables' is not defined

In [2]:
class Student:
    name="Ajay"
    roll_no=22


In [3]:
student1 = Student()#object1
#objectname.variable
print(student1.name)
print(student1.roll_no)


Ajay
22


In [4]:
student2=Student()#object2
#objectname.varaiable=newvalue
student2.name="Deesha"
student2.roll_no=32

print(student2.name,student2.roll_no)


Deesha 32


In [5]:
class Shape:
    sides=2
    def display(self):
        print(self.sides)
        
line = Shape()
line.display()


2


In [6]:
triangle=Shape()
triangle.sides=3
triangle.display()


3


In [7]:
rectangle=Shape()
rectangle.sides=4
rectangle.display()

4


In [8]:
class Sample:
    age=35 #global
    def show(self):
        age2=40 #local
        print("age is", self.age)
        print("age2 is" , age2)
        
s=Sample()
s.show()
s2=Sample()
s2.age=45
s2.age2=50 #no change
s.show()


age is 35
age2 is 40
age is 35
age2 is 40


In [4]:
class Employee:
    empid=99
    name="raj"
    salary= 90000
    designation="operation manger"
    def show (self):
        print("name", self.name)
        print("salary", self.salary)
        print("designation", self.designation)
        s= Employee()
        s.show

# CONSTRUCTOR

In [ ]:
special function with __init__(self):
dunder method/function
init: initialization
initialize variables when objects are created
it is implicitly called


In [1]:
class Sample:
    def __init__(self):
        print("hi i am constructor")
    def display(self):
        print("i am from display function")
        
        
s=Sample()
s.display()


hi i am constructor
i am from display function


In [3]:
class Sample:
    def __init__(self):
        print("hi i am jones from Della Infotech")
    def display(self):
        print("i live and work in trichy")
        
        
s=Sample()
s.display()

hi i am jones from Della Infotech
i live and work in trichy


In [4]:
class Student:
    def __init__(self,n,r,m):
        self.name=n
        self.roll_no=r
        self.marks=m
    def display(self):
        print("name:",self.name)
        print("roll_no",self.roll_no)
        print("marks:",self.marks)
        
s1=Student("abc",23,80)
s1.display()
s2=Student("amruta",25,89)
s2.display()

name: abc
roll_no 23
marks: 80
name: amruta
roll_no 25
marks: 89


In [10]:
class Circle():
    def __init__(self,r):
        self.r=r
    def display(self):
        return math.pi*(self.r**2)
 
s=Circle(10)
s.display()

NameError: name 'math' is not defined

In [11]:
class Circle:
    def __init__(self,r):
        self.pi=3.14
        self.radius=r
    def area(self):
        area=self.pi*(self.radius**2)
        print("area of circle",area)
        
        
a1=Circle(5)
a1.area()

a2=Circle(10)
a2.area()


area of circle 78.5
area of circle 314.0


In [7]:
class Student:
    def __init__(self,n,r,e,m,h):
        self.name=n
        self.roll_no=r
        self.english=e
        self.maths=m
        self.history=h
    def marks (self):
        total=self.english+self.maths+self.history
        percentage=total/300*100
        print("total=", total)
        print("percentage=", percentage)
        if percentage>75:
            print("A")
        elif percentage>50:
            print("2ndclass")
        elif percentage>60:
            print("1stclass")
        else:
            ("fail")

s=Student("jones",24,75,60,80)
s.marks()
    

total= 215
percentage= 71.66666666666667
2ndclass


In [8]:
class Student:
    def __init__(self,r,n,m=[]):
        self.rollno=r
        self.name=n
        self.marks=m
        
    def display(self):
        print(self.rollno)
        sum=0
        for i in self.marks:
            sum=sum+i
        print(sum)
        
        
        
student1=Student(1,'xyz',[70,89,67,88,90])
student1.display()


1
404


In [9]:
class ListSample:
    def __init__(self,l=[]):
        self.list1=l
        for i in self.list1:
            print(i)
            

list2=[1,2,3,4,5]
lt=ListSample(list2)


1
2
3
4
5


In [ ]:
class Circle: pi = 3.14 def init(self, diameter):

print("Creating circle with diameter {d}".format(d=diameter))
# Add assignment for self.radius here:
1.Even though we usually know the diameter beforehand, what we need for most calculations is the radius.

In Circle‘s constructor set the instance variable self.radius to equal half the diameter that gets passed in. 2.Define three Circles with three different diameters.

A medium pizza, medium_pizza, that is 12 inches across. Your teaching table, teaching_table, which is 36 inches across. The Round Room auditorium, round_room, which is 11,460 inches across. 3.Define a new method circumference for your circle object that takes only one argument, self, and returns the circumference of a circle with the given radius by this formula:

circumference = 2 * pi * radius 4.Print out the circumferences of medium_pizza, teaching_table, and round_room.


In [10]:
class Circle:
    pi = 3.14
    def __int__(self, diameter):
        print("Creating circle with diameter {d}".format(d=diameter))
        self.radius=diameter/2
        
    def circumference(self):
        circumference = 2*self.pi*self.radius
        return circumference
    
    medium_pizza=Circle(12)
    teaching_table=Circle(36)
    round_room=Circle(11460)
    
print(medium_pizza.circumference())
print(teaching_table.circumference())
print(round_room.circumference())


NameError: name 'Circle' is not defined

In [11]:
class Student():
    def __init__(self):
        print("What is your name?")
        self.name="Pritam"
        
    def my_name(self):
        return("my name is "+self.name)
s1=Student()
print(s1.my_name())


What is your name?
my name is Pritam


In [ ]:
class Example:

    def __init__(self,name,department,salary):
        self.name=name
        self.department=department
        self.salary=salary
        
    def display(self):
        print(self.name,self.department,self.salary)
        
        
        
e1=Example(input("enter name"),input("enter department"),int(input("enter salry")))
e2=Example(input("enter name"),input("enter department"),int(input("enter salry")))
e1.display()
e2.display()
e3=e2
e3.display()


enter namejones
enter departmentengg
enter salry33000


In [ ]:
class Employee:
    name="xyz"
    designation="manager"
    salary=23000
    
    def display(self):
        print("name of employee",self.name)
        print("designation:",self.designation)
        print("salary:",self.salary)
        
        
e1=Employee()# object name=classname()
e1.display()
e1.name="srujana"
e1.display()

e2=Employee()

e2.name="priya"
e2.designation="developer"
e2.salary=30000

e2.display()


In [ ]:
class Circle:
  pi = 3.14
  def __init__(self, diameter):
    
    print("Creating circle with diameter {d}".format(d=diameter))
    # Add assignment for self.radius here:
    self.radius=diameter/2
  def circumference(self):
    circumference = 2 * self.pi * self.radius
    return circumference
medium_pizza=Circle(12)
teaching_table=Circle(36)
round_room=Circle(11460)
print(medium_pizza.circumference())
print(teaching_table.circumference())
print(round_room.circumference())


In [1]:
#divide each element of list by 5 without numpy
a=[10,20,30,40,50]
b=[]
for i in a:
    b.append(i/5)
    
print(b)


print(type(a))
print(type(b))


[2.0, 4.0, 6.0, 8.0, 10.0]
<class 'list'>
<class 'list'>


In [3]:
c=[i/2 for i in a]
c


[5.0, 10.0, 15.0, 20.0, 25.0]

In [4]:
import numpy as np


In [5]:
a=np.array([10,20,30,40,50])
print(a)
print(type(a))


[10 20 30 40 50]
<class 'numpy.ndarray'>


In [6]:
b=a/5
print(b)


[ 2.  4.  6.  8. 10.]


In [7]:
c=a+b
print(c)


[12. 24. 36. 48. 60.]


In [8]:
print(type(b))
print(type(c))


<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [9]:
c=a*b
print(c)

[ 20.  80. 180. 320. 500.]


In [10]:
c=a*a
print(c)

[ 100  400  900 1600 2500]


In [11]:
test_1 = np.array([92, 94, 88, 91, 87])
test_2 = np.array([79, 100, 86, 93, 91])
test_3 = np.array([87, 85, 72, 90, 92])


In [12]:
teacher identified problem in test 3 that scores are less by 3 marks so create variable test_3_fixed and update test3 score
then calculate total of all tests scores
total_grade
create variable final_grade which will store average of tests score


SyntaxError: invalid syntax (756044727.py, line 1)

In [13]:
test_3 = np.array([87, 85, 72, 90, 92])
total_grade=test_3_fixed
print(total_grade)


NameError: name 'test_3_fixed' is not defined

In [14]:
test_1 = np.array([92, 94, 88, 91, 87])
test_2 = np.array([79, 100, 86, 93, 91])
test_3 = np.array([87, 85, 72, 90, 92])
test=sum test_1

SyntaxError: invalid syntax (1259156702.py, line 4)

In [15]:
test_1 = np.array([92, 94, 88, 91, 87]) 
total_grade1=np.sum(test_1)  
total_grade1

452

In [17]:
test_1 = np.array([92, 94, 88, 91, 87])
test_2 = np.array([79, 100, 86, 93, 91])
test_3 = np.array([87, 85, 72, 90, 92])

total_grade2=np.sum(test_2)  
total_grade2


449

In [18]:
test_1 = np.array([92, 94, 88, 91, 87])
test_2 = np.array([79, 100, 86, 93, 91])
test_3 = np.array([87, 85, 72, 90, 92])

total_grade3=np.sum(test_3)  
total_grade3

426

In [19]:
test_1 = np.array([92, 94, 88, 91, 87])
test_2 = np.array([79, 100, 86, 93, 91])
test_3 = np.array([87, 85, 72, 90, 92])

test_3_sum= test_3 +3
print(test_3_sum)

[90 88 75 93 95]


In [20]:
samp_arr = np.genfromtxt("sample.csv",delimiter =",")
print(samp_arr)
print(type(samp_arr))


[20. 30. 40. 50.]
<class 'numpy.ndarray'>


In [21]:
s=np.array(([2,4,6],[8,10,12]),ndmin=2)
print(s)

s=np.array([1,2,3,4,5,6])
print(s)

s=np.array([1,2,3,4],dtype=complex)
print(s)


[[ 2  4  6]
 [ 8 10 12]]
[1 2 3 4 5 6]
[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


In [22]:
a=[[1,3,5],[2,4,6]]
b=np.array(a)
print(b)


[[1 3 5]
 [2 4 6]]


In [23]:
print(type(b))


<class 'numpy.ndarray'>


In [24]:
combined = np.array([[92, 94, 88, 91, 87],
                    [79, 100, 86, 93, 91],
                    [87, 85, 72, 90, 92]])

print(combined)
print(type(combined))


[[ 92  94  88  91  87]
 [ 79 100  86  93  91]
 [ 87  85  72  90  92]]
<class 'numpy.ndarray'>


In [25]:
combined.shape #3 rows and 5 columns


(3, 5)

In [26]:
combined[2]


array([87, 85, 72, 90, 92])

In [27]:
combined[0]


array([92, 94, 88, 91, 87])

In [28]:
combined[0,1] #row,column


94

In [29]:
combined[:,1] #all rows for column one


array([ 94, 100,  85])

In [30]:
combined[1,:] #row 1 all column


array([ 79, 100,  86,  93,  91])

In [31]:
combined[0:2,1:3]


array([[ 94,  88],
       [100,  86]])

In [32]:
combined[0:3,2:3]

array([[88],
       [86],
       [72]])

In [33]:
a=np.array([10,9,7,34,56,100,52,2,4])
print(a>50)


[False False False False  True  True  True False False]


In [34]:
print(a[a>50])


[ 56 100  52]


In [35]:
print(a[a%2==0])


[ 10  34  56 100  52   2   4]


In [36]:
student_scores = np.array([[92, 94, 88, 91, 87],
                           [79, 100, 86, 93, 91],
                           [87, 85, 72, 90, 92]])

#Display marks greater than 90
#display marks bwtween 90 to 95

In [37]:
print(student_scores[student_scores>90])

[ 92  94  91 100  93  91  92]


In [41]:
print(student_scores[(student_scores>90) & (student_scores<95)])

[92 94 91 93 91 92]


In [ ]:
Today we’re visiting the Goldilocks Porridge Festival, sampling a selection of breakfast cereals and judging them based on their temperature (listed in Fahrenheit). porridge = np.array([79, 65, 50, 63, 56, 90, 85, 98, 79, 51])

##Create a logical condition that selects samples in the porridge array that are less than 60, and save them to a variable named cold.

##2. Create a logical condition that finds all the samples that are higher than 80 and save them to a variable named hot.

##3. Create a logical condition that finds all the samples that are between 60 and 80 (inclusive) and save them to a variable named just_right.

##4. Print each array to the terminal.

In [44]:
porridge = np.array([79, 65, 50, 63, 56, 90, 85, 98, 79, 51])
cold = porridge[porridge<60]
hot= porridge[porridge>80]
just_right = (porridge[(porridge>60) & (porridge<=80)])
print(cold)
print(hot)
print(just_right)


[50 56 51]
[90 85 98]
[79 65 63 79]


In [45]:
x=np.empty((3,2),dtype=int)
print(x)
print("---------------------------------------")
# array of five zeros
x=np.zeros(5,dtype=int)
print(x)
print("---------------------------------------")
x=np.zeros(5)
print(x)

print("---------------------------------------")


[[92 94]
 [91 93]
 [91 92]]
---------------------------------------
[0 0 0 0 0]
---------------------------------------
[0. 0. 0. 0. 0.]
---------------------------------------


In [46]:
sample = np.array([1,2,3,4,5,5,5,6,7,8,9,10,5])
print(np.mean(sample))
print("-------------------------")
print(np.median(sample))
print("-------------------------")

print(np.sort(sample))
print("-------------------------")
print(np.min(sample))
print("-------------------------")
print(np.max(sample))
print("-------------------------")
print(np.std(sample))
print("-------------------------")


5.384615384615385
-------------------------
5.0
-------------------------
[ 1  2  3  4  5  5  5  5  6  7  8  9 10]
-------------------------
1
-------------------------
10
-------------------------
2.527950265408459
-------------------------


In [47]:
print(np.percentile(sample,75)) #third quartile


7.0


In [48]:
print(np.percentile(sample,25))#first quartile


4.0


In [49]:
print(np.percentile(sample,50))


5.0


In [50]:
print(np.percentile(sample,1))


1.12


In [ ]:
After the river in your town flooded during a recent hurricane, you've become interested in collecting data about the its height. Every day for the past month, you walk to the river, measure the height of the water, and enter this information into a notebook


In [51]:
water_height = np.array([4.01, 4.03, 4.27, 4.29, 4.19,
                         4.15, 4.16, 4.23, 4.29, 4.19,
                         4.00, 4.22, 4.25, 4.19, 4.10,
                         4.14, 4.03, 4.23, 4.08, 14.20,
                         14.03, 11.20, 8.19, 6.18, 4.04,
                         4.08, 4.11, 4.23, 3.99, 4.23])
mean=np.mean(water_height)
#to find the average water height:
sort=np.sort(water_height)
#sort our data to see if there could be any measurements to throw our data
median=np.median(water_height)
#measure the median to see if its more representative of the dataset
per=np.percentile(water_height,50) 
#median tells us where half of our data lies
deviation=np.std(water_height)
#standard deviation to understand how similar or 
#how different each data point is


In [52]:
print("mean:",mean)
print(".............................................................................")
print("sorted:",sort)
print(".............................................................................")
print("median:",median)
print(".............................................................................")
print("per:",per)
print(".............................................................................")
print("deviation:",deviation)
print(".............................................................................")


mean: 5.251
.............................................................................
sorted: [ 3.99  4.    4.01  4.03  4.03  4.04  4.08  4.08  4.1   4.11  4.14  4.15
  4.16  4.19  4.19  4.19  4.22  4.23  4.23  4.23  4.23  4.25  4.27  4.29
  4.29  6.18  8.19 11.2  14.03 14.2 ]
.............................................................................
median: 4.19
.............................................................................
per: 4.19
.............................................................................
deviation: 2.784585367099861
.............................................................................


In [3]:
a=5
float(a)
a

5

In [6]:
13//2
#quotioent part

6

In [8]:
13%2
#reminder part

1

In [11]:
#convert float to integer
x=24.0
x=int(x)
x


24

In [21]:
#convert integer to complex
a=6
b=9.0
c = complex(a,b)
c

(6+9j)

In [24]:
#convert string to integer
a=int(input("enter number"))
b=int(input("enter number"))
c=a+b
print(c)

enter number12
enter number12
24


In [3]:
a=[2,"jones","tamilnadu",24,1997]
a[-1]
a[2]
a[0]

2

In [1]:
#tuples
a=["ajith","jones",12,(1+3j)]
a=[1]


In [2]:
a=((1,4,7,4,9))
type(a)


tuple

In [3]:
#dictionary
#key and value

a={'s':6, 'j':6}



In [4]:
a.values()

dict_values([6, 6])

In [5]:
a.keys()

dict_keys(['s', 'j'])

In [7]:
#set
aset={2,5,7,3}
aset

{2, 3, 5, 7}

In [3]:
a=24 , b=3
a<=b

SyntaxError: cannot assign to literal (3921790810.py, line 1)

In [4]:
#string concatenation +
"tea" + "pot"

'teapot'

In [5]:
"jones" + "1997"

'jones1997'

In [1]:
list1 = [1, 2, 3]
list2 = [6, 7, 8]
list1 + list2


[1, 2, 3, 6, 7, 8]

In [2]:
items1=["apple","orange","grapes"]
items2=["carrot","potato","cabbage"]
items1.append(items2)
print(items1)

['apple', 'orange', 'grapes', ['carrot', 'potato', 'cabbage']]


In [3]:
a= int(input("Enter a number "))
if a == 5:
    print("It's True")    
else:
    print("It's Flase")
    
print("Welcome")


Enter a number 6
It's Flase
Welcome


In [4]:
#if,elif,else
a = int(input("Enter a number "))
if a == 3:
    print("Ajith")
elif a == 3:
    print("Kumar")
else:
    print("Ajith Kumar")


Enter a number 24
Ajith Kumar


In [5]:
a= int(input("Enter the number"))
if  a<5:
    print(" I am Less than 5 ")
elif    5<=a<10:
     print( " I am between 5 & 10 ")

elif 10<=a<15:
    print(" I am between 10 & 15 ")


else:
    print ( " I am Greater than 15 ")


Enter the number10
 I am between 10 & 15 


In [6]:
a= int(input("Enter the number"))
b= int(input("Enter the number"))
if a%b==0:
    print("its divisible")
else:
    print("not divisible")


Enter the number45
Enter the number12
not divisible


In [7]:
a = int(input('enter number : '))
b = int(input('enter number : '))
if a % b == 0:
    print("It is divisible")
    #print('{} is divisible by {}'.format(a,b))
else:
    print("It is no divisible")
     #print('{} is not divisible by {}'.format(a,b))


enter number : 12
enter number : 14
It is no divisible


In [8]:
# if a n b are even no then print
a=int(input("enter a 1 no"))
b=int(input("enter a  2 no"))
if a%2==0 and b%2==0:
    print("sum of square of no",a**2+b**2)
elif a%2==1 and b%2==1:    
    print("sum of cube of no",a**3+b**3)
else:
    print("sum",a+b)


enter a 1 no25
enter a  2 no35
sum of cube of no 58500


In [ ]:
Student = input("Enter your name = ")
sub1 = input("Enter your subject-1 = ")
marks1 = int(input("Enter your marks = "))
sub2 = input("Enter your subject-2 = ")
marks2 = int(input("Enter your marks = "))
sub3 = input("Enter your subject-3 = ")
marks3 = int(input("Enter your marks = "))
sub4 = input("Enter your subject-4 = ")
marks4 = int(input(" Enter your marks = "))
sub5 = input("Enter your sub-5 = ")
marks5 = int(input("Enter your marks = "))
print('Student name is {}'.format(Student))
print('You have scored {} marks in {} subject'.format(marks1,sub1))
print('You have scored {} marks in {} subject'.format(marks2,sub2))
print('You have scored {} marks in {} subject'.format(marks3,sub3))
print('You have scored {} marks in {} subject'.format(marks4,sub4))
print('You have scored {} marks in {} subject'.format(marks5,sub5))
print('Total marks scored is {} out of 500'.format(marks1+marks2+marks3+marks4+marks5))


Enter your name = 45
Enter your subject-1 = 65
Enter your marks = 863
Enter your subject-2 = 28
Enter your marks = 54
Enter your subject-3 = 121


In [ ]:
for i in seq:
    print(i)


In [ ]:
for item in seq:
    print('Yep')


In [ ]:
list(range(10,20))


# Lambda Function or annoymnous function

In [4]:
cube = lambda a : a*a*a
result =f(6)
print(Result)


NameError: name 'f' is not defined

In [1]:
a = 5
b = 0
try:
    print(a/b)
except:
    print("Hello")
finally:
    print('Riji')


Hello
Riji


In [2]:
try:
    {
        #print( 2 / var1 )
        print(var)
    }
except TypeError as e:
    {
        print("You cannot divide an int and a string") 
    }
except ZeroDivisionError as e:
    {
        print("You cannot divide a number by 0")
         
    }
except Exception as e:
    {
        print("Some other error")
    }


Some other error


In [3]:
var1 = 0
try:
    {
        #print( 2 / var1 )
        print(var)
    }
except TypeError as e:
    {
        print("You cannot divide an int and a string") 
    }
except ZeroDivisionError as e:
    {
        print("You cannot divide a number by 0")
         
    }
except Exception as e:
    {
        print("Some other error")
    }
finally:
    print("EduBridge")


Some other error
EduBridge


In [4]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])


NameError: name 'np' is not defined

In [5]:
#Create an array with 5 dimensions and verify that it has 5 dimensions:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)


NameError: name 'np' is not defined

In [3]:
class demo:
    def abc(Self,a,b):
        return a+b
    a = demo()
    a.abc(2,2)

NameError: name 'demo' is not defined

In [4]:
## Banking case study

# main_balance ---- 0
# check_balance()---- print my main_balance
# deposit()---- MB---> x(amount)----> MB+x---> MB
# withdraw()----MB--->y(amount)----> y-MB----->MB
#MB > y---> sucess
# -----insufficient funds


In [5]:
class Recharge:
    main balance = 0
    def check_balance(self):
    
    print('main balance', self.main balance)

    def deposit(self,x):
        self.main balance = self.main balance + x
        print('cash deposited:',x)
        
    def withdraw(Self,y):
        if self.main balance >=y:
            self.main balance = self.main balance - y
            print('the amount debited:' ,y)
        else:
            print('insufficent balence')

SyntaxError: invalid syntax (4061537594.py, line 2)

In [7]:
import numpy as np
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.zeros(5,dtype = complex)

array([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j])

In [9]:
np.ones(4)

array([1., 1., 1., 1.])

In [10]:
np.ones(3)*5

array([5., 5., 5.])

In [1]:
#single inhertiance
class Animal:
    def speak(self):
        print("Animal cannot speak")
class Dog (Animal):
    def bark(self):
        print("dog can bark")
        

In [2]:
obj = Dog()
obj.bark()
obj.speak()


dog can bark
Animal cannot speak


In [3]:
#multiple inheritance
class Parent:
    def fun1(self):
        print("hey this is fun1")
class Parent2:
    def fun2(self):
        print("hey this is fun2")
class Child(Parent,Parent2):
    def fun3(Self):
        print("hey this is fun3")
        

In [5]:
obj = Child()
obj.fun1()
obj.fun2()
obj.fun3()


hey this is fun1
hey this is fun2
hey this is fun3


In [6]:
#multilevel inheritance
class Parent:
    def fun1(self):
        print("hey this is fun1")
class Parent1(Parent):
    def fun2(self):
        print("hey this is fun2")
class Parent2(Parent1):
    def fun3(Self):
        print("hey this is fun3")
class Parent3(Parent2):
    def fun4(self):
        print("hey this is fun4")
    

In [8]:
obj = Parent3()
obj.fun1()
obj.fun2()
obj.fun3()
obj.fun4()

hey this is fun1
hey this is fun2
hey this is fun3
hey this is fun4


In [9]:
#polymorphism

class India():
    def capital(self):
        print("new delhi")
    def lang(self):
        print("hindi")
class USA():
    def capital(self):
        print("washington, DC")
    def lang (Self):
        print("english")
        

In [12]:
obj1 = India()
obj1.captial()
obj1.lang()


AttributeError: 'India' object has no attribute 'captial'

In [1]:
#multithreading
class Hello:
    def run(self):
        for i in range(5):
            print("Hello")
class Hi:
    def run(self):
        for i in range(5):
            print("Hi") 
o1=Hello()
o2=Hi()

o1.run()
o2.run()


Hello
Hello
Hello
Hello
Hello
Hi
Hi
Hi
Hi
Hi


In [3]:
class Hello (Thread):
    def run (self):
        for i in range (5):
            print("Hello")
class Hi (Thread):
    def run(self):
        for i in range(5):
            print("Hi")

t1= Hello()
t2= Hi()

t1.start()
sleep(0.2)
t2.start()

        

NameError: name 'Thread' is not defined

In [8]:
import numpy as np
import arr as array
a = np.array([10,20,30,40,50])
arr[1:5:3]

ModuleNotFoundError: No module named 'arr'

In [9]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)

#Show
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
import numpy as np
import random as randn
np.random.seed(101)
randn(5,4)

TypeError: 'module' object is not callable

In [4]:
df = pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())
df


NameError: name 'pd' is not defined

In [5]:
df = pd.DataFrame({'A':[1,2,np.nan,1,1,1],
                  'B':[5,np.nan,np.nan,2,2,2],
                  'C':[1,2,3,1,2,3]})


NameError: name 'pd' is not defined

In [6]:
df.fillna(df['C'].mode()[0])


NameError: name 'df' is not defined

In [ ]:
import pandas as pd
import numpy as np

In [1]:
df = pd.read_csv('cs2m.csv')

NameError: name 'pd' is not defined

In [1]:
import pandas as pd
# Create dataframe
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}


In [2]:
df = pd.DataFrame(data)


In [3]:
df.groupby('Company')


In [4]:
by_comp.mean()


NameError: name 'by_comp' is not defined